env: product-dev99
spring:
  application:
    name: product
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///pm111?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
server:
  port: 8083
