spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///pm111
  redis:
    host: localhost
    port: 6739
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9090
